#modules 

In [13]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import ipywidgets as widgets
from IPython.display import display, clear_output

#Implement vector and matrix operations (dot product, cross product, matrix multiplication).

In [4]:

#Vector stuff
vector_a = np.array(np.arange(1, 7, 2))
vector_b = np.array(np.arange(2, 8, 2))

dot_product = np.dot(vector_a, vector_b)
cross_product = np.cross(vector_a, vector_b)

print(f"Vector A: {vector_a}\n")
print(f"Vector B: {vector_b}\n")
print(f"Dot Product: {dot_product}\n")
print(f"Cross Product: {cross_product}\n")


#Matrix stuff
matrix_A = np.array([
    (np.arange(1,4)),
    (np.arange(4,7)),
    (np.arange(7,10))
])
matrix_B = np.array([
    np.arange(10, 13),
    np.arange(13, 16),
    np.arange(16, 19)
])
matrix_product = np.matmul(matrix_A, matrix_B)

print(f"Matrix A: \n{matrix_A}\n")
print(f"Matrix B: \n{matrix_B}\n")
print(f"Matrix Product: \n{matrix_product}\n")


Vector A: [1 3 5]

Vector B: [2 4 6]

Dot Product: 44

Cross Product: [-2  4 -2]

Matrix A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B: 
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Matrix Product: 
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]



#Vector Addition visualization 
#Play with different values with slides

In [23]:
# Vector addition Visualization

def create_vector_plot():

    # Create the figure and axes objects
    def customize_graph(fig, ax):
        # Set the background color of the figure and axes
        fig.patch.set_facecolor('#1f2021')
        ax.patch.set_facecolor('#1f2021')

        # Set the color of the grid
        ax.tick_params(axis='x', colors='white', labelsize=9)
        ax.tick_params(axis='y', colors='white', labelsize=9)

        # Set the color of the axes labels and title
        ax.spines["bottom"].set_position("zero")
        ax.spines["left"].set_position("zero")

        # Hide the top and right spines
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        # Set color for remaining spines
        ax.spines["bottom"].set_color("white")
        ax.spines["left"].set_color("white")

        # Set the color of the tick params
        ax.set_xlim([-10, 20])
        ax.set_ylim([-10, 20])

        # Set the color of the tick labels and title

    # Create a function that plots a vector and return the arrow object
    def plot_vector(ax, vector=[1, 1], color='red', label='vector', starting_position_vector=[0, 0]):
        return ax.arrow(
            starting_position_vector[0], starting_position_vector[1],
            vector[0], vector[1],
            length_includes_head=True, head_width=0.5, head_length=0.5,
            fc=color, ec=color, label=label
        )

    # Create a function that updates the plot based on the slider values
    def update_plot(vector_ax, vector_ay, vector_bx, vector_by):

        clear_output(wait=True) #Clear the output cell
        # Create new figure
        fig,ax = plt.subplots(figsize=(10, 10))
        customize_graph(fig,ax)

         # Define colors for vectors
        color_a = '#00FFFF'  # Color for Vector A (cyan)
        color_b = '#FFA500'  # Color for Vector B (orange)
        color_c = '#32CD32'  # Color for Vector C (green)

        # Create and plot vectors
        vector_a = np.array([vector_ax, vector_ay])
        vector_b = np.array([vector_bx, vector_by])
        vector_c = vector_a + vector_b

        # Plot the vectors as arrows
        arrow_a =  plot_vector(ax, vector_a, color_a, 'Vector A')
        arrow_b = plot_vector(ax, vector_b, color_b, 'Vector B', vector_a)
        arrow_c = plot_vector(ax, vector_c, color_c , 'Vector C')

        # Create dummy lines for the legend
        legend_lines = [
            mlines.Line2D([0], [0], color = color_a, lw=2, label="Vector A"),  # Vector A (cyan)
            mlines.Line2D([0], [0], color = color_b, lw=2, label="Vector B"),  # Vector B (orange)
            mlines.Line2D([0], [0], color = color_c , lw=2, label="Vector C")   # Vector C (green)
        ]
        ax.legend(handles = legend_lines,loc = 'upper right', fontsize = 8)

        ax.set_title(f"Vector_c = [ {vector_c[0]} , {vector_c[1]} ]", fontsize = 12, color = "white")

        #Add image of vector addition to the plot
        plt.savefig('vector_plot.png', bbox_inches='tight')  # Save with tight layout

        plt.close() #Prevents memory leaks by properly closing unused figures

        display(fig)


    # Create sliders for vector components
    vector_ax_slider = widgets.FloatSlider(value=2, min=-10, max=10, step=0.5, description='Vector A x:')
    vector_ay_slider = widgets.FloatSlider(value=6, min=-10, max=10, step=0.5, description='Vector A y:')
    vector_bx_slider = widgets.FloatSlider(value=7, min=-10, max=10, step=0.5, description='Vector B x:')
    vector_by_slider = widgets.FloatSlider(value=3, min=-10, max=10, step=0.5, description='Vector B y:')

    interactive_plot = widgets.interactive(
        update_plot, vector_ax=vector_ax_slider, vector_ay=vector_ay_slider,
        vector_bx=vector_bx_slider, vector_by=vector_by_slider
    )

    display(interactive_plot)

create_vector_plot()

interactive(children=(FloatSlider(value=2.0, description='Vector A x:', max=10.0, min=-10.0, step=0.5), FloatS…